# Generated by Django 4.2.7 on 2025-08-15 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizations.organization')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='projects_organiz_ca8931_idx'), models.Index(fields=['due_date'], name='projects_due_dat_67b3bf_idx')],
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
